### ISSUE TITLE
UI enhancement: ETH wrapping for auction

### ISSUE THREAD

**Issue by Ro5s** [sushiswap/miso#19]
similar to how Sushi AMM app provides ETH -> wETH wrapping functionality, we might introduce this directly into MISO auction UI to simplify steps to adding commitments -- perhaps by showing a `wrap` button in lieu of `approve` if user balance is `0`?

![image](https://user-images.githubusercontent.com/41117279/131717277-982a7a6c-6a57-48d1-8e93-8a461338d8a8.png)

also, see https://twitter.com/mysticryuujin/status/1433124807546134534?s=20

**Comment by matthewlilley** [comment]
@Ro5s closing this because I think ETH commitments are good now.
