### ISSUE TITLE
enhancement: add all events needed to allow a subgraph to rely on event handlers only

### ISSUE THREAD

**Issue by LufyCZ** [sushiswap/miso#32]
For example, this event should also fire somewhere in the `initMarket` function, as the time is set there as well. 

https://github.com/sushiswap/miso/blob/638d6de749e2a364d58a36cd097fd03712115674/contracts/Auctions/BatchAuction.sol#L98

https://github.com/sushiswap/miso/blob/638d6de749e2a364d58a36cd097fd03712115674/contracts/Auctions/BatchAuction.sol#L149-L150

https://github.com/sushiswap/miso/blob/638d6de749e2a364d58a36cd097fd03712115674/contracts/Auctions/BatchAuction.sol#L438-L450

We should also consider adding completely new events for, among others, the `initMarket` function, as it is currently not possible to track things like `token` or `paymentCurrency` on the subgraph without resorting to call handlers

Proposing these:
- `AuctionDeployed(address funder, address admin, address wallet, address token, uint256 totalTokens, address paymentCurrency, address pointList`
- `AuctionFinalized()` => `AuctionFinalized(bool successful)`
- `PointListUpdated(address pointList, bool enabled)`
- `TokensWithdrawn(address token, address to, address amount)`

Might add more if I think of any

**Comment by matthewlilley** [comment]
@LufyCZ open a PR with all events needed to remove reliancy of call handlers
